# Generated by Django 6.0.1 on 2026-02-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade_estoque', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('data_entrada', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
