# Generated by Django 6.0.1 on 2026-02-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebidas',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='bebidas/'),
        ),
    ]
