# Generated by Django 6.0.1 on 2026-02-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_bebidas_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebidas',
            name='url_foto',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
