# Generated by Django 6.0.1 on 2026-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_bebidas_url_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebidas',
            name='e_destaque',
            field=models.BooleanField(default=False),
        ),
    ]
