# Generated by Django 6.0.1 on 2026-02-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_bebidas_e_destaque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebidas',
            name='quantidade_estoque',
        ),
        migrations.AddField(
            model_name='bebidas',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bebidas',
            name='categoria',
            field=models.CharField(choices=[('Cerveja', 'Cerveja'), ('Vinho', 'Vinho'), ('Destilado', 'Destilado'), ('NaoAlcoolico', 'Sem Álcool')], default='Cerveja', max_length=50),
        ),
    ]
