# Generated by Django 6.0.1 on 2026-02-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_bebidas_quantidade_estoque_bebidas_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidas',
            name='e_destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque no Site'),
        ),
    ]
